[project]
org-name = "ballerina"
version = "@toml.version@"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "math"
    version = "@project.version@"
    path = "../math-native/build/libs/math-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["math"]
